---
title: "A Study of Beers and Breweries in the US"
author: "Ryan Quincy Paul & Chad Madding"
date: "October 18, 2018"
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

*With a strong presence across the 50 states and the District of Columbia, craft breweries are a vibrant and flourishing economic force at the local, state and national level. As consumers continue to demand a wide range of high quality, full-flavored beers, small and independent craft brewers are meeting this growing demand with innovative offerings, creating high levels of economic value in the process.*

**Bart Watson**, Chief Economist for the Brewers Association

https://www.brewersassociation.org/statistics/economic-impact-data/

This project will focus on gaining insite into breweries in the United Stated. We will focus on providing information to a national brewey for them to look into investing in the craft brewery indrestry.

## Questions

   1. How many breweries are present in each state?
   
   2. Merge beer data with the breweries data. Print the first 6 observations and the last six observations to check the merged file.
   
   3. Report the number of NA's in each column.
   
   4. Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.
   
   5. Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer?
   
   6. Summary statistics for the ABV variable.
   
   7. Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot.
   
## Conclusion

Summarize your findings from this exercise.
